# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # ✅ Convertir la variable d'environnement en paramètre Symfony
    app.admin_email: '%env(APP_ADMIN_EMAIL)%'
    app.siret: '%env(APP_SIRET)%'  # À définir dans .env
    app.ape: '%env(APP_APE)%'
    # Vos autres paramètres existants
    app.uploads.projects: '%kernel.project_dir%/public/uploads/projects'
    app.uploads.skills: '%kernel.project_dir%/public/uploads/skills'
    app.uploads.projects.gallery: '%kernel.project_dir%/public/uploads/projects/gallery'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # Services personnalisés
    App\Service\ProjectService:
        public: true

    App\Service\ContactService:
        public: true

    App\Service\ImageUploadService:
        public: true
        arguments:
            $projectsDirectory: '%kernel.project_dir%/public/uploads/projects'
            $skillsDirectory: '%kernel.project_dir%/public/uploads/skills'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
